export const OPPORTUNITIES = [
  {
    slug: "anthropic-series-h",
    type: "growth-equity",
    badge: "Growth Equity",
    status: "open",
    statusLabel: "Accepting Investors",
    banner: "/home/invest/royal-banner.png",
    logo: "/home/invest/royal-logo.png",
    title: "Anthropic — AI Safety & Foundation Models",
    token: "USD / USDT",
    sector: "Artificial Intelligence",
    stage: "Late Stage (Pre-IPO)",
    minInvestment: "$10,000",
    raised: 4200000,
    target: 10000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Anthropic is an AI safety company building reliable, interpretable AI systems. Founded by former OpenAI researchers, it develops Claude — a family of AI assistants deployed across enterprise. Revenue run rate exceeded $4B in 2025. Co-investors include Google, Spark Capital, and Lightspeed.",
    highlights: ["Revenue run rate: $4B+ (2025)", "Valuation: $61.5B (Series H)", "Co-investors: Google, Lightspeed", "IPO filing underway"],
    tags: ["AI", "Foundation Models", "Pre-IPO", "SaaS"],
    featured: true,
    investors: 312,
    daysLeft: 18,
    ytdReturn: null,
    coInvestors: ["Google", "Spark Capital", "Lightspeed Venture Partners"],
    source: "OurCrowd AI Fund portfolio company",
  },
  {
    slug: "databricks-series-j",
    type: "growth-equity",
    badge: "Growth Equity",
    status: "open",
    statusLabel: "Accepting Investors",
    banner: "/home/invest/royal-banner.png",
    logo: "/home/invest/royal-logo.png",
    title: "Databricks — Data Intelligence Platform",
    token: "USD / USDT",
    sector: "Enterprise Software / AI",
    stage: "Late Stage (Pre-IPO)",
    minInvestment: "$25,000",
    raised: 6800000,
    target: 15000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Databricks is the world's leading data intelligence platform, combining data engineering, machine learning, and AI analytics in one unified system. 10,000+ global customers including 60% of the Fortune 500. $3.5B ARR as of 2025. Partnership with Anthropic for enterprise AI agents.",
    highlights: ["ARR: $3.5B (2025)", "Customers: 10,000+ enterprise", "60% of Fortune 500", "Founded: 2013, San Francisco"],
    tags: ["Data Platform", "AI", "Enterprise", "Pre-IPO"],
    featured: true,
    investors: 487,
    daysLeft: 31,
    ytdReturn: null,
    coInvestors: ["Andreessen Horowitz", "Tiger Global", "NEA"],
    source: "OurCrowd portfolio company",
  },
  {
    slug: "groq-series-c",
    type: "venture",
    badge: "Venture",
    status: "open",
    statusLabel: "Accepting Investors",
    banner: "/home/invest/kpoproad-banner.png",
    logo: "/home/invest/kpoproad-logo.png",
    title: "Groq — AI Inference Chips (LPU)",
    token: "USD / USDT",
    sector: "AI Hardware / Semiconductors",
    stage: "Series C",
    minInvestment: "$5,000",
    raised: 2100000,
    target: 5000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Groq manufactures Language Processing Units (LPUs) — purpose-built chips for ultra-fast AI inference, delivering 10-18x faster inference than GPUs. GroqCloud serves developers globally. Raised $640M led by BlackRock in 2024. $1.5B commitment from Saudi Arabia for national AI infrastructure.",
    highlights: ["Raised $640M (BlackRock led, 2024)", "$1.5B Saudi Arabia commitment", "10-18x faster than GPU inference", "Co-investors: Samsung, Cisco, KDDI"],
    tags: ["AI Chips", "Hardware", "Infrastructure", "LPU"],
    featured: false,
    investors: 228,
    daysLeft: 45,
    ytdReturn: null,
    coInvestors: ["BlackRock", "Neuberger Berman", "Samsung Catalyst Fund"],
    source: "OurCrowd AI Fund portfolio company",
  },
  {
    slug: "scale-ai-series-f",
    type: "venture",
    badge: "Venture",
    status: "open",
    statusLabel: "Accepting Investors",
    banner: "/home/invest/kpoproad-banner.png",
    logo: "/home/invest/kpoproad-logo.png",
    title: "Scale AI — AI Data Infrastructure",
    token: "USD / USDT",
    sector: "AI Data / Infrastructure",
    stage: "Series F",
    minInvestment: "$10,000",
    raised: 3400000,
    target: 8000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Scale AI provides the data infrastructure and human feedback services that power AI development for the world's leading AI labs, defense agencies, and enterprises. Customers include OpenAI, Meta, and the US Department of Defense. Valued at $13.8B in its latest round.",
    highlights: ["Valuation: $13.8B (Series F)", "Customers: OpenAI, Meta, US DoD", "AI data labeling market leader", "Founder: Alexandr Wang (age 27)"],
    tags: ["AI Infrastructure", "Data", "Defense", "Enterprise"],
    featured: false,
    investors: 196,
    daysLeft: 27,
    ytdReturn: null,
    coInvestors: ["Accel", "Tiger Global", "Index Ventures"],
    source: "OurCrowd portfolio company",
  },
  {
    slug: "quantum-machines-series-b",
    type: "venture",
    badge: "Venture",
    status: "coming-soon",
    statusLabel: "Waitlist Open",
    banner: "/home/invest/klove-pet-banner.png",
    logo: "/home/invest/klove-pet-logo.png",
    title: "Quantum Machines — Quantum Computing Control",
    token: "USD / USDT",
    sector: "Quantum Computing",
    stage: "Series B",
    minInvestment: "$5,000",
    raised: 0,
    target: 3000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Quantum Machines builds the universal quantum computing control hardware and software stack used by leading quantum labs and corporations worldwide. Raised $100M in 2025. Partners include IBM, Intel, and national quantum programs across the US, Europe, and Asia.",
    highlights: ["Raised $100M (2025)", "Universal quantum control platform", "Partners: IBM, Intel, IQM", "Jerusalem-based deep tech"],
    tags: ["Quantum Computing", "Deep Tech", "Hardware", "Israel"],
    featured: false,
    investors: 0,
    daysLeft: null,
    ytdReturn: null,
    coInvestors: ["Battery Ventures", "Maor Investments", "Meron Capital"],
    source: "OurCrowd portfolio company",
  },
  {
    slug: "zutacore-series-b",
    type: "venture",
    badge: "Venture",
    status: "closed",
    statusLabel: "Round Closed",
    banner: "/home/invest/klove-pet-banner.png",
    logo: "/home/invest/klove-pet-logo.png",
    title: "ZutaCore — AI Data Center Cooling",
    token: "USD / USDT",
    sector: "AI Infrastructure / CleanTech",
    stage: "Series B",
    minInvestment: "$5,000",
    raised: 2800000,
    target: 2800000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "ZutaCore specializes in two-phase direct liquid cooling for AI servers and HPC data centers — eliminating water use while dramatically improving efficiency. Partnership with SoftBank and Foxconn for NVIDIA AI server deployments. First successful use in NVIDIA accelerated computing chips.",
    highlights: ["Partners: SoftBank, Foxconn, NVIDIA", "Waterless liquid cooling", "AI server deployment at scale", "OurCrowd AI Fund portfolio"],
    tags: ["CleanTech", "AI Infrastructure", "Cooling", "Israel"],
    featured: false,
    investors: 143,
    daysLeft: 0,
    ytdReturn: null,
    coInvestors: ["SoftBank", "Foxconn", "NVIDIA Inception"],
    source: "OurCrowd AI Fund portfolio company",
  },
];

export const NEWS_ARTICLES = [
  { id: 1, category: "Portfolio Update", categoryColor: "#36E8CA", title: "Anthropic files for IPO after $65B valuation — Specfin investors positioned for exit", excerpt: "Anthropic has confidentially filed for an initial public offering following its Series H at a $61.5B valuation. Early investors via OurCrowd-style platforms are tracking significant mark-ups from previous rounds.", date: "2026-06-15", readTime: "4 min", author: "Specfin Research Team" },
  { id: 2, category: "Market Insight", categoryColor: "#9FB6D0", title: "Databricks hits $3.5B ARR — why enterprise AI data platforms are the new infrastructure", excerpt: "Databricks continued its extraordinary growth in 2025, reaching $3.5B in annual recurring revenue. 60% of the Fortune 500 now runs on its Data Intelligence Platform, and the Anthropic partnership positions it at the center of enterprise AI.", date: "2026-06-12", readTime: "5 min", author: "Ark Global Research" },
  { id: 3, category: "Deep Tech", categoryColor: "#7C3AED", title: "Groq raises $640M from BlackRock, secures $1.5B Saudi Arabia AI commitment", excerpt: "Groq's Language Processing Units are proving that purpose-built AI inference chips can outperform general-purpose GPUs by 10-18x. The Saudi Arabia commitment signals the beginning of national AI infrastructure deployments.", date: "2026-06-10", readTime: "6 min", author: "Specfin Research Team" },
  { id: 4, category: "Venture Trends", categoryColor: "#EFC878", title: "Private market AI valuations: how to think about late-stage pre-IPO investing in 2026", excerpt: "With Anthropic, Databricks, and SpaceX all in various stages of public market preparation, accredited investors face a narrow window to access private valuations. We break down the risk/return calculus.", date: "2026-06-08", readTime: "7 min", author: "Specfin Editorial" },
  { id: 5, category: "Israel Tech", categoryColor: "#00A896", title: "Quantum Machines raises $100M: why quantum computing control is the bottleneck no one talks about", excerpt: "Without reliable quantum control hardware, quantum computers cannot be programmed at scale. Quantum Machines has quietly built the universal control stack that every major quantum lab depends on.", date: "2026-06-05", readTime: "6 min", author: "Specfin Research Team" },
  { id: 6, category: "Investor Guide", categoryColor: "#60A5E0", title: "Carry fees, SPVs, and co-investments: a plain-English guide to how Specfin structures deals", excerpt: "Most private equity investments charge 2% management and 20% carry. Here is exactly what that means for your returns, how SPVs work, and why co-investment rights matter.", date: "2026-06-02", readTime: "5 min", author: "Specfin Editorial" },
];

export const EVENTS = [
  { id: 1, type: "Investor Briefing", typeColor: "#36E8CA", title: "Specfin Portfolio Briefing: AI Sector Update — Anthropic, Databricks, Groq", description: "Quarterly portfolio company briefing covering the latest milestones from Specfin's AI investment opportunities. Includes financial highlights, competitive landscape analysis, and Q&A with the investment team.", date: "2026-07-10", time: "7:00 PM KST / 11:00 AM BST", duration: "60 min", speakers: ["Jake Park, CIO", "Specfin Investment Team"], attendees: 487, virtual: true },
  { id: 2, type: "Deep Dive", typeColor: "#0D3880", title: "The LPU vs GPU debate: Groq, Cerebras, and the AI inference chip wars", description: "A technical and investment deep dive into the AI inference chip sector. Why purpose-built inference chips may outperform general GPU infrastructure for AI deployment, and what this means for investors.", date: "2026-07-17", time: "6:00 PM KST", duration: "45 min", speakers: ["Dr. David Choi, Technical Advisor"], attendees: 312, virtual: true },
  { id: 3, type: "Summit", typeColor: "#EFC878", title: "Specfin Seoul Private Market Summit 2026", description: "First annual in-person summit in Seoul. Presentations from Specfin portfolio company representatives, keynotes from the founding team, and a networking reception. Co-hosted with Ark Global.", date: "2026-08-22", time: "9:00 AM KST", duration: "Full day", speakers: ["Jake Park, CEO", "Min-Ji Lee, CTO", "Ark Global Team"], attendees: 156, virtual: false, location: "Grand InterContinental Seoul, Gangnam" },
  { id: 4, type: "Masterclass", typeColor: "#9F84FF", title: "How to evaluate pre-IPO tech companies: valuation, dilution, and exit scenarios", description: "A practical masterclass on evaluating late-stage private market investments. Topics: how to read a cap table, understanding dilution risk, modeling exit scenarios, and comparing private vs public valuations.", date: "2026-07-24", time: "5:00 PM KST", duration: "75 min", speakers: ["Specfin Investment Committee"], attendees: 543, virtual: true },
];

export const PORTFOLIO_HOLDINGS = [
  { id: 1, name: "Anthropic (Series G SPV)", type: "Growth Equity", invested: 25000, currentValue: 41250, returnPct: 65.0, status: "Active", since: "2024-08-15", currency: "USD" },
  { id: 2, name: "Databricks (Series J)", type: "Growth Equity", invested: 50000, currentValue: 78500, returnPct: 57.0, status: "Active", since: "2024-11-20", currency: "USD" },
  { id: 3, name: "Groq (Series B SPV)", type: "Venture", invested: 10000, currentValue: 14200, returnPct: 42.0, status: "Active", since: "2024-06-01", currency: "USD" },
  { id: 4, name: "ZutaCore (Series B)", type: "Venture", invested: 5000, currentValue: 6800, returnPct: 36.0, status: "Active", since: "2024-03-10", currency: "USD" },
];

export const ASSET_CLASSES = [
  { icon: "🚀", title: "Growth Equity (Pre-IPO)", description: "Late-stage private companies preparing for IPO. Access Anthropic, Databricks, SpaceX and similar companies before they go public — the stage where institutional returns are typically made.", href: "/dashboard/opportunities?type=growth-equity", stats: "2 open · Avg. $37B valuation", color: "#0D3880" },
  { icon: "⚡", title: "Venture Capital", description: "Series A-C technology startups across AI infrastructure, deep tech, and enterprise software. OurCrowd-sourced deals from Israel's most active VC ecosystem, co-invested with top global funds.", href: "/dashboard/opportunities?type=venture", stats: "4 opportunities · $5K min", color: "#00A896" },
  { icon: "🏢", title: "Real World Assets (RWA)", description: "Tokenized fractional ownership of commercial real estate, blue-chip art, and physical collectibles. Quarterly USDT dividends. Secondary market liquidity. Live NAV on-chain. Launching Phase 2.", href: "/dashboard/opportunities?type=rwa", stats: "Phase 2 launching Q3 2026", color: "#7C3AED" },
];

export const LEARN_ARTICLES = [
  { id: 1, category: "Getting Started", title: "How to evaluate a pre-IPO investment on Specfin", description: "A complete guide to reading a term sheet, understanding carry and management fees, and assessing the exit path for late-stage private companies.", readTime: "6 min" },
  { id: 2, category: "AI Investing", title: "The AI infrastructure stack: where Anthropic, Groq, and Databricks fit", description: "A visual framework for understanding the AI value chain — from chips to models to applications — and where OurCrowd-backed companies sit in it.", readTime: "7 min" },
  { id: 3, category: "Portfolio Strategy", title: "How to build a diversified private market portfolio", description: "Stage diversification (seed vs growth), sector balance, and position sizing for a private market portfolio. Lessons from OurCrowd's 480+ company portfolio.", readTime: "5 min" },
  { id: 4, category: "Tax & Legal", title: "SPVs explained: how Specfin structures co-investments", description: "Special Purpose Vehicles (SPVs) are the legal structure used for most co-investment deals. Here's how they work, what you own, and how distributions flow.", readTime: "5 min" },
  { id: 5, category: "Risk Management", title: "Liquidity risk in private markets: what you need to know", description: "Private market investments are illiquid by design. This guide covers lock-up periods, secondary market options, and how to think about liquidity needs before investing.", readTime: "6 min" },
];
