export const OPPORTUNITIES = [
  { slug:"specfin-alpha-fund-i", type:"hedge-fund", badge:"Hedge Fund Strategy", status:"open", statusLabel:"Accepting Investors", banner:"/home/invest/royal-banner.png", logo:"/home/invest/royal-logo.png", title:"Specfin Alpha Fund I — Multi-Strategy Quant", token:"USDT / KRW", sector:"Quantitative Trading", stage:"Phase 1", minInvestment:"$500 USDT", raised:1240000, target:5000000, returnTarget:"18–24% p.a.", fee:"30% performance (10–15% Gold tier)", description:"Verified quant professionals manage a multi-strategy fund across crypto perpetuals and traditional equities. All trades executed via smart contract and recorded on-chain. Audited vault — fund manager cannot withdraw without pre-defined conditions.", highlights:["On-chain verification","Audited vault","30-day lock-up","Monthly reports"], tags:["Quant","Multi-Strategy","On-Chain"], featured:true, investors:47, daysLeft:23, ytdReturn:18.4 },
  { slug:"spectra-liquidity-fund", type:"hedge-fund", badge:"Hedge Fund Strategy", status:"open", statusLabel:"Accepting Investors", banner:"/home/invest/royal-banner.png", logo:"/home/invest/royal-logo.png", title:"Spectra Liquidity Fund — BTC/ETH Market Making", token:"USDT / USDC", sector:"Market Making", stage:"Phase 1", minInvestment:"$2,000 USDT", raised:870000, target:3000000, returnTarget:"12–16% p.a.", fee:"25% performance", description:"Professional market-making strategy on BTC and ETH perpetual futures. Tight bid-ask spreads generate consistent returns with low correlation to market direction. Non-custodial via audited smart contract.", highlights:["Market-neutral","BTC + ETH","Daily liquidity","Non-custodial"], tags:["Market Making","BTC","ETH"], featured:true, investors:29, daysLeft:41, ytdReturn:14.1 },
  { slug:"gangnam-district-b-rwa", type:"rwa", badge:"RWA Asset", status:"coming-soon", statusLabel:"Phase 2 — Waitlist", banner:"/home/invest/kpoproad-banner.png", logo:"/home/invest/kpoproad-logo.png", title:"Gangnam District B — Fractional Commercial Building", token:"USDT", sector:"Commercial Real Estate", stage:"Phase 2", minInvestment:"$1,000 USDT", raised:0, target:12000000, returnTarget:"7.2% p.a. quarterly USDT", fee:"1.5% management", description:"Fractional ownership of a prime Seoul commercial property in Gangnam District B. Custodied by licensed Korean securities firm. Quarterly USDT dividends. Live NAV on-chain.", highlights:["Licensed Korean custodian","Quarterly USDT dividends","Secondary market","Live NAV"], tags:["Real Estate","Seoul","Dividend"], featured:false, investors:0, daysLeft:null, ytdReturn:null },
  { slug:"itaewon-art-collective", type:"rwa", badge:"RWA Asset", status:"coming-soon", statusLabel:"Phase 2 — Waitlist", banner:"/home/invest/klove-pet-banner.png", logo:"/home/invest/klove-pet-logo.png", title:"Itaewon Art Collective — Blue-Chip Korean Art", token:"USDT", sector:"Fine Art", stage:"Phase 2", minInvestment:"$500 USDT", raised:0, target:3500000, returnTarget:"6–10% p.a. est.", fee:"2% management", description:"Fractional ownership of 12 blue-chip Korean contemporary artworks with verified provenance. Quarterly valuation updates. Tradeable on Specfin secondary market at Phase 2.", highlights:["12 artworks","Independent appraisal","Secondary market","Quarterly valuations"], tags:["Art","Korean","Collectibles"], featured:false, investors:0, daysLeft:null, ytdReturn:null },
  { slug:"kpop-road-krst", type:"token-sale", badge:"Token Sale", status:"closed", statusLabel:"Closed", banner:"/home/invest/kpoproad-banner.png", logo:"/home/invest/kpoproad-logo.png", title:"Kpop Road — $KRST", token:"$KRST", sector:"K-pop / Entertainment", stage:"Vanguard Round", minInvestment:"$100 USDT", raised:200000, target:200000, returnTarget:"Variable", fee:"None", description:"KpopRoad offers 300 exclusive NFTs providing VIP access to K-pop events, rewards, and virtual performances. Built on Solana. Independent security audit completed.", highlights:["Solana NFT","VIP K-pop access","Independent audit","300 supply"], tags:["NFT","K-pop","Solana"], featured:false, investors:183, daysLeft:0, ytdReturn:null },
  { slug:"klove-pet-kpet", type:"token-sale", badge:"Token Sale", status:"closed", statusLabel:"Closed", banner:"/home/invest/klove-pet-banner.png", logo:"/home/invest/klove-pet-logo.png", title:"K-Love Pet — $KPET", token:"$KPET", sector:"Pet Care / DeFi", stage:"Vanguard Round", minInvestment:"$50 USDT", raised:200000, target:200000, returnTarget:"Variable", fee:"None", description:"K-Love Pet is a blockchain-powered pet care loyalty ecosystem. Token holders earn rewards for pet care activities and access K-pet community events across Korea and Japan.", highlights:["Pet loyalty","Korea & Japan","Community rewards","DeFi"], tags:["Pet Care","Loyalty","DeFi"], featured:false, investors:204, daysLeft:0, ytdReturn:null },
];

export const NEWS_ARTICLES = [
  { id:1, category:"Platform Update", categoryColor:"#36E8CA", title:"Specfin Alpha Fund I reaches 25% of target raise in first 30 days", excerpt:"The platform's flagship quant strategy has attracted 47 investors in its first month, raising $1.24M of its $5M target.", date:"2026-06-20", readTime:"3 min", author:"Specfin Research Team" },
  { id:2, category:"Market Insight", categoryColor:"#9FB6D0", title:"Korean commercial real estate: why Gangnam remains a top-tier institutional hold", excerpt:"With vacancy rates below 2% and average annual rental yield of 6.8%, Gangnam District remains one of Asia's most attractive commercial real estate markets.", date:"2026-06-18", readTime:"5 min", author:"Ark Global Research" },
  { id:3, category:"Blockchain", categoryColor:"#7C3AED", title:"Smart contract audit complete: Specfin Alpha Fund I vault passes all security checks", excerpt:"Independent auditors have verified the fund vault's security model. No critical vulnerabilities found. Full audit report available to investors.", date:"2026-06-15", readTime:"4 min", author:"Security Team" },
  { id:4, category:"Education", categoryColor:"#EFC878", title:"What is a performance fee and how does Spectra tier reduce yours?", excerpt:"Standard performance fee is 30%. Gold tier Spectra holders pay just 10–15%. Here is how the math works on a $10,000 profit.", date:"2026-06-12", readTime:"6 min", author:"Specfin Editorial" },
  { id:5, category:"RWA", categoryColor:"#00A896", title:"Tokenized real estate: How Specfin Phase 2 will work with Korean securities law", excerpt:"In partnership with licensed Korean securities firms, Phase 2 will allow fractional ownership with full regulatory compliance.", date:"2026-06-10", readTime:"7 min", author:"Legal & Compliance" },
  { id:6, category:"Investor Guide", categoryColor:"#60A5E0", title:"USDT vs KRW: Which deposit method is right for you?", excerpt:"Specfin accepts both KRW bank transfer and USDT/USDC wallet deposits. A breakdown of speed, fees, and considerations for each.", date:"2026-06-08", readTime:"4 min", author:"Specfin Editorial" },
];

export const EVENTS = [
  { id:1, type:"Webinar", typeColor:"#36E8CA", title:"Specfin Platform Walkthrough — Live Q&A", description:"Join the founding team for a full platform walkthrough. Learn how to set up your investor account, browse opportunities, and track your portfolio.", date:"2026-07-08", time:"7:00 PM KST", duration:"60 min", speakers:["Jake Park, CEO","Min-Ji Lee, CTO"], attendees:234, virtual:true },
  { id:2, type:"Deep Dive", typeColor:"#0D3880", title:"Hedge Fund Strategy Deep Dive: How Quant Funds Work On-Chain", description:"A technical session exploring how Specfin's quantitative trading strategies are structured, executed, and verified on-chain.", date:"2026-07-15", time:"6:00 PM KST", duration:"45 min", speakers:["David Choi, Head of Quant"], attendees:157, virtual:true },
  { id:3, type:"Summit", typeColor:"#EFC878", title:"Specfin Seoul Investor Summit 2026", description:"Our first in-person investor summit in Seoul. Presentations from fund managers, RWA partners, and keynote from the Specfin founding team.", date:"2026-08-20", time:"9:00 AM KST", duration:"Full day", speakers:["Full team + guests"], attendees:89, virtual:false, location:"Gangnam, Seoul" },
  { id:4, type:"AMA", typeColor:"#9F84FF", title:"Ask Me Anything: RWA Tokenization & Korean Securities Law", description:"Open Q&A with Specfin's legal and compliance team on RWA tokenization within the Korean regulatory framework.", date:"2026-07-22", time:"5:00 PM KST", duration:"60 min", speakers:["Legal Team"], attendees:312, virtual:true },
];

export const PORTFOLIO_HOLDINGS = [
  { id:1, name:"Specfin Alpha Fund I", type:"Hedge Fund", invested:2000, currentValue:2368, returnPct:18.4, status:"Active", since:"2026-03-01", currency:"USDT" },
  { id:2, name:"Kpop Road $KRST", type:"Token Sale", invested:300, currentValue:210, returnPct:-30, status:"Closed", since:"2025-11-15", currency:"USDT" },
  { id:3, name:"Spectra Liquidity Fund", type:"Hedge Fund", invested:3000, currentValue:3423, returnPct:14.1, status:"Active", since:"2026-04-10", currency:"USDT" },
];

export const ASSET_CLASSES = [
  { icon:"📊", title:"Hedge Fund Strategies", description:"Access institutional-grade quantitative and multi-strategy hedge funds managed by verified professional traders. All trades recorded on-chain. Subscribe and mirror automatically.", href:"/dashboard/opportunities?type=hedge-fund", stats:"2 active funds · Avg. 16.2% YTD", color:"#0D3880" },
  { icon:"🏢", title:"Real World Assets (RWA)", description:"Fractional ownership of tokenized commercial real estate, blue-chip art, and physical collectibles. Quarterly USDT dividends. Secondary market liquidity. Live NAV on-chain.", href:"/dashboard/opportunities?type=rwa", stats:"Phase 2 launching soon", color:"#00A896" },
  { icon:"🪙", title:"Token Sales", description:"Pre-vetted early-stage token sales, NFT collections, and DeFi protocol launches. All projects independently audited before listing. Spectra holders get whitelist priority.", href:"/dashboard/opportunities?type=token-sale", stats:"2 completed · $400K raised", color:"#7C3AED" },
];

export const LEARN_ARTICLES = [
  { id:1, category:"Getting Started", title:"How to make your first investment on Specfin", description:"A complete step-by-step guide from account creation to confirmed position, for both cash and crypto investors.", readTime:"5 min" },
  { id:2, category:"Hedge Funds", title:"Understanding performance fees and how Spectra reduces yours", description:"How performance fees work, and how Spectra tier reduces your fee from 30% to 10–15%.", readTime:"4 min" },
  { id:3, category:"RWA", title:"What is a tokenized real-world asset and how does it work?", description:"How physical assets like buildings and art are fractionally tokenized and made investable on-chain.", readTime:"6 min" },
  { id:4, category:"Blockchain", title:"How on-chain trade verification protects investors", description:"Why every Specfin trade being permanently recorded on-chain is a fundamental protection against fraud.", readTime:"5 min" },
  { id:5, category:"Tax & Legal", title:"Korean 가상자산 과세: what Specfin investors need to know", description:"A practical guide to Korean cryptocurrency tax law and how Specfin annual tax reports work.", readTime:"8 min" },
];
