export const OPPORTUNITIES = [
  {
    slug: "anthropic-series-h",
    type: "growth-equity",
    badge: "Growth Equity",
    status: "open",
    statusLabel: "Accepting Investors",
    banner: "/logos/anthropic-banner.svg",
    logo: "/logos/anthropic.svg",
    title: "Anthropic — AI Safety & Foundation Models",
    token: "USD / USDT",
    sector: "Artificial Intelligence",
    stage: "Late Stage (Pre-IPO)",
    minInvestment: "$10,000",
    raised: 4200000,
    target: 10000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Anthropic is an AI safety company building reliable, interpretable AI systems. Founded by former OpenAI researchers, it develops Claude — a family of AI assistants deployed across enterprise. Revenue run rate exceeded $4B in 2025. IPO filing underway.",
    highlights: ["Revenue run rate: $4B+ (2025)", "Valuation: $61.5B (Series H)", "IPO filing underway", "Co-investors: Google, Lightspeed"],
    tags: ["AI", "Foundation Models", "Pre-IPO", "SaaS"],
    featured: true, investors: 312, daysLeft: 18, ytdReturn: null,
    coInvestors: ["Google", "Spark Capital", "Lightspeed Venture Partners"],
    source: "OurCrowd AI Fund portfolio company",
  },
  {
    slug: "databricks-series-j",
    type: "growth-equity",
    badge: "Growth Equity",
    status: "open",
    statusLabel: "Accepting Investors",
    banner: "/logos/databricks-banner.svg",
    logo: "/logos/databricks.svg",
    title: "Databricks — Data Intelligence Platform",
    token: "USD / USDT",
    sector: "Enterprise Software / AI",
    stage: "Late Stage (Pre-IPO)",
    minInvestment: "$25,000",
    raised: 6800000,
    target: 15000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Databricks is the world's leading data intelligence platform. $3.5B ARR as of 2025. 10,000+ enterprise customers including 60% of the Fortune 500. Strategic partnership with Anthropic for enterprise AI agents expected to generate $100M in revenue over five years.",
    highlights: ["ARR: $3.5B (2025)", "10,000+ enterprise customers", "60% of Fortune 500", "Anthropic partnership: $100M rev target"],
    tags: ["Data Platform", "AI", "Enterprise", "Pre-IPO"],
    featured: true, investors: 487, daysLeft: 31, ytdReturn: null,
    coInvestors: ["Andreessen Horowitz", "Tiger Global", "NEA"],
    source: "OurCrowd portfolio company",
  },
  {
    slug: "spacex-pre-ipo",
    type: "growth-equity",
    badge: "Growth Equity",
    status: "open",
    statusLabel: "Accepting Investors",
    banner: "/logos/spacex-banner.svg",
    logo: "/logos/spacex.svg",
    title: "SpaceX — Commercial Space & Starlink",
    token: "USD / USDT",
    sector: "Space Technology / Satellite Internet",
    stage: "Late Stage (Pre-IPO)",
    minInvestment: "$10,000",
    raised: 2178000,
    target: 8000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "SpaceX is the world's most valuable private company at a $2.1T valuation following its record Nasdaq IPO debut. Starlink operates the world's largest satellite internet constellation with 6M+ subscribers globally. OurCrowd listed the late-stage opportunity in 2025 at ~$800B valuation.",
    highlights: ["Valuation: $2.1T (post-IPO)", "Starlink: 6M+ subscribers", "OurCrowd listed 2025 at $800B", "Space Force contract: $4.16B"],
    tags: ["SpaceTech", "Satellite", "Pre-IPO", "Elon Musk"],
    featured: false, investors: 341, daysLeft: 12, ytdReturn: null,
    coInvestors: ["Google", "Fidelity", "Baillie Gifford"],
    source: "OurCrowd portfolio company — Reg D filing 2025",
  },
  {
    slug: "xai-series-c",
    type: "growth-equity",
    badge: "Growth Equity",
    status: "open",
    statusLabel: "Accepting Investors",
    banner: "/logos/xai-banner.svg",
    logo: "/logos/xai.svg",
    title: "xAI — Grok & Frontier AI (Elon Musk)",
    token: "USD / USDT",
    sector: "Artificial Intelligence",
    stage: "Late Stage",
    minInvestment: "$10,000",
    raised: 2038000,
    target: 7000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "xAI is Elon Musk's frontier AI company developing Grok, a real-time AI assistant integrated with X (Twitter). Valued at $250B. Announced merger with SpaceX to create a $1.5T combined 'vertically integrated innovation engine'. OurCrowd listed the Reg D offering in 2025.",
    highlights: ["Valuation: $250B", "SpaceX merger: $1.5T combined", "Grok integrated into X (Twitter)", "OurCrowd Reg D offering 2025"],
    tags: ["AI", "Frontier Model", "Elon Musk", "Pre-IPO"],
    featured: false, investors: 278, daysLeft: 9, ytdReturn: null,
    coInvestors: ["Andreessen Horowitz", "Sequoia Capital", "Fidelity"],
    source: "OurCrowd portfolio company — Reg D filing 2025",
  },
  {
    slug: "hailo-series-c",
    type: "venture",
    badge: "Venture",
    status: "open",
    statusLabel: "Accepting Investors",
    banner: "/logos/hailo-banner.svg",
    logo: "/logos/hailo.svg",
    title: "Hailo — AI Edge Processors",
    token: "USD / USDT",
    sector: "AI Hardware / Edge Computing",
    stage: "Series C",
    minInvestment: "$5,000",
    raised: 1900000,
    target: 5000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Hailo develops purpose-built AI inference chips for edge computing — embedded in cameras, vehicles, smart city infrastructure, and industrial systems. Hailo-8 and Hailo-10H deliver datacenter-level AI performance at edge power envelopes. OurCrowd made a follow-on investment in 2026.",
    highlights: ["Edge AI chip market leader (Israel)", "OurCrowd follow-on investment 2026", "Customers: automotive, smart city, industrial", "NVIDIA Inception program partner"],
    tags: ["AI Chips", "Edge Computing", "Israel", "Hardware"],
    featured: false, investors: 184, daysLeft: 38, ytdReturn: null,
    coInvestors: ["ABB Technology Ventures", "NEC", "Verizon Ventures"],
    source: "OurCrowd portfolio company — follow-on 2026",
  },
  {
    slug: "groq-series-c",
    type: "venture",
    badge: "Venture",
    status: "open",
    statusLabel: "Accepting Investors",
    banner: "/logos/groq-banner.svg",
    logo: "/logos/groq.svg",
    title: "Groq — AI Inference Chips (LPU)",
    token: "USD / USDT",
    sector: "AI Hardware / Semiconductors",
    stage: "Series C",
    minInvestment: "$5,000",
    raised: 2100000,
    target: 5000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Groq manufactures Language Processing Units (LPUs) — purpose-built chips delivering 10-18x faster AI inference than GPUs. GroqCloud serves developers globally. Raised $640M led by BlackRock in 2024. $1.5B commitment from Saudi Arabia for national AI infrastructure.",
    highlights: ["Raised $640M (BlackRock led, 2024)", "$1.5B Saudi Arabia commitment", "10-18x faster than GPU inference", "GroqCloud: enterprise developer platform"],
    tags: ["AI Chips", "Hardware", "Infrastructure", "LPU"],
    featured: false, investors: 228, daysLeft: 45, ytdReturn: null,
    coInvestors: ["BlackRock", "Neuberger Berman", "Samsung Catalyst Fund"],
    source: "OurCrowd AI Fund portfolio company",
  },
  {
    slug: "scale-ai-series-f",
    type: "venture",
    badge: "Venture",
    status: "open",
    statusLabel: "Accepting Investors",
    banner: "/logos/scale-banner.svg",
    logo: "/logos/scale.svg",
    title: "Scale AI — AI Data Infrastructure",
    token: "USD / USDT",
    sector: "AI Data / Infrastructure",
    stage: "Series F",
    minInvestment: "$10,000",
    raised: 3400000,
    target: 8000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Scale AI provides the data infrastructure and human feedback services that power the world's leading AI labs, defense agencies, and enterprises. Customers include OpenAI, Meta, and the US Department of Defense. Valued at $13.8B. Founder Alexandr Wang is the youngest self-made billionaire.",
    highlights: ["Valuation: $13.8B (Series F)", "Customers: OpenAI, Meta, US DoD", "AI data labeling market leader", "Founder: Alexandr Wang (youngest billionaire)"],
    tags: ["AI Infrastructure", "Data", "Defense Tech", "Enterprise"],
    featured: false, investors: 196, daysLeft: 27, ytdReturn: null,
    coInvestors: ["Accel", "Tiger Global", "Index Ventures"],
    source: "OurCrowd portfolio company",
  },
  {
    slug: "classiq-series-b",
    type: "venture",
    badge: "Venture",
    status: "coming-soon",
    statusLabel: "Waitlist Open",
    banner: "/logos/classiq-banner.svg",
    logo: "/logos/classiq.svg",
    title: "Classiq — Quantum Computing Software",
    token: "USD / USDT",
    sector: "Quantum Computing / Enterprise Software",
    stage: "Series B",
    minInvestment: "$5,000",
    raised: 0,
    target: 3000000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Classiq provides the universal software platform for quantum algorithm development. Used by Sumitomo Corp and Mizuho-DL Financial Technology for quantum Monte Carlo simulations in finance. Classiq's platform compresses quantum circuits and makes quantum computing accessible to enterprise developers without deep physics expertise.",
    highlights: ["Sumitomo Corp quantum finance project", "Mizuho-DL Financial Technology partner", "Universal quantum algorithm platform", "Jerusalem-based deep tech"],
    tags: ["Quantum Computing", "Enterprise SaaS", "Israel", "Deep Tech"],
    featured: false, investors: 0, daysLeft: null, ytdReturn: null,
    coInvestors: ["HPE Pathfinder", "NTT", "Samsung Ventures"],
    source: "OurCrowd portfolio company — Classiq Technologies",
  },
  {
    slug: "cyabra-series-a",
    type: "venture",
    badge: "Venture",
    status: "coming-soon",
    statusLabel: "Waitlist Open",
    banner: "/logos/cyabra-banner.svg",
    logo: "/logos/cyabra.svg",
    title: "Cyabra — AI Disinformation Intelligence",
    token: "USD / USDT",
    sector: "Cybersecurity / Social Intelligence",
    stage: "Series A",
    minInvestment: "$5,000",
    raised: 0,
    target: 2500000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "Cyabra uses AI to detect fake accounts, bot networks, and coordinated disinformation campaigns on social media. Customers include governments, financial institutions, and media organizations. Board includes former US Secretary of State Mike Pompeo. OurCrowd was lead investor in its Series A.",
    highlights: ["Lead investor: OurCrowd (Series A)", "Board: Mike Pompeo (ex-US Sec. of State)", "Customers: governments, banks, media", "Cited in New York Times, Reuters"],
    tags: ["Cybersecurity", "AI", "Disinformation", "GovTech"],
    featured: false, investors: 0, daysLeft: null, ytdReturn: null,
    coInvestors: ["Harpoon", "TAU Ventures"],
    source: "OurCrowd lead investor — Series A",
  },
  {
    slug: "zutacore-series-b",
    type: "venture",
    badge: "Venture",
    status: "closed",
    statusLabel: "Round Closed",
    banner: "/logos/zutacore-banner.svg",
    logo: "/logos/zutacore.svg",
    title: "ZutaCore — AI Data Center Cooling",
    token: "USD / USDT",
    sector: "AI Infrastructure / CleanTech",
    stage: "Series B",
    minInvestment: "$5,000",
    raised: 2800000,
    target: 2800000,
    returnTarget: "Capital appreciation",
    fee: "20% carry, 2% management",
    description: "ZutaCore specializes in waterless two-phase direct liquid cooling for AI servers and HPC data centers. Partnership with SoftBank and Foxconn: first successful deployment in NVIDIA accelerated computing chips. OurCrowd invested in 2024 and highlighted as a key investment that year.",
    highlights: ["Partners: SoftBank, Foxconn, NVIDIA", "First NVIDIA AI server deployment", "Waterless: zero evaporative cooling", "OurCrowd 2024 highlighted investment"],
    tags: ["CleanTech", "AI Infrastructure", "Cooling", "Israel"],
    featured: false, investors: 143, daysLeft: 0, ytdReturn: null,
    coInvestors: ["SoftBank", "Foxconn", "NVIDIA Inception"],
    source: "OurCrowd AI Fund portfolio company",
  },
];

export const NEWS_ARTICLES = [
  { id: 1, category: "Portfolio Update", categoryColor: "#36E8CA", title: "Anthropic files for IPO — Specfin investors positioned for exit at $61.5B valuation", excerpt: "Anthropic has confidentially filed for an IPO following its Series H. OurCrowd's AI Fund invested at a $17B valuation and has tracked a significant mark-up. Early platform investors are now watching for the public listing timeline.", date: "2026-06-15", readTime: "4 min", author: "Specfin Research Team" },
  { id: 2, category: "Portfolio Update", categoryColor: "#36E8CA", title: "SpaceX hits $2.1T valuation after record Nasdaq IPO — what it means for OurCrowd investors", excerpt: "SpaceX debuted on Nasdaq to record-breaking demand, sending its market cap to $2.1T. OurCrowd listed the investment opportunity in 2025 at approximately $800B valuation, representing a 2.5x multiple for platform investors.", date: "2026-06-12", readTime: "5 min", author: "Specfin Research Team" },
  { id: 3, category: "Deep Tech", categoryColor: "#7C3AED", title: "Groq raises $640M from BlackRock, secures $1.5B Saudi Arabia AI infrastructure deal", excerpt: "Groq's Language Processing Units are delivering 10-18x faster AI inference than GPUs. The Saudi Arabia commitment signals the beginning of national AI infrastructure deployments at sovereign scale.", date: "2026-06-10", readTime: "6 min", author: "Specfin Research Team" },
  { id: 4, category: "Market Insight", categoryColor: "#9FB6D0", title: "Databricks hits $3.5B ARR — the Anthropic partnership and why enterprise AI platforms are the new OS", excerpt: "Databricks reached $3.5B in ARR and 60% Fortune 500 penetration in 2025. Its partnership with Anthropic to build enterprise AI agents is expected to generate $100M in revenue over five years.", date: "2026-06-08", readTime: "5 min", author: "Ark Global Research" },
  { id: 5, category: "Israel Tech", categoryColor: "#00A896", title: "Hailo, Classiq, Cyabra: OurCrowd's Israeli deep tech portfolio making global impact", excerpt: "Three OurCrowd portfolio companies from Israel are quietly becoming global infrastructure: Hailo for edge AI chips, Classiq for quantum software, and Cyabra for AI disinformation detection used by governments worldwide.", date: "2026-06-05", readTime: "7 min", author: "Specfin Research Team" },
  { id: 6, category: "Investor Guide", categoryColor: "#60A5E0", title: "Pre-IPO investing in 2026: Anthropic, SpaceX, xAI — the window is narrowing", excerpt: "With Anthropic filing for IPO and SpaceX already public, the window to access these companies at private valuations is closing. We break down which OurCrowd-backed opportunities remain open and at what terms.", date: "2026-06-02", readTime: "6 min", author: "Specfin Editorial" },
];

export const EVENTS = [
  { id: 1, type: "Investor Briefing", typeColor: "#36E8CA", title: "Specfin AI Portfolio Briefing: Anthropic, Databricks, Groq, Hailo", description: "Quarterly briefing on Specfin's AI investment opportunities. Financial highlights, competitive landscape for AI chips vs foundation models, and live Q&A with the investment team.", date: "2026-07-10", time: "7:00 PM KST / 11:00 AM BST", duration: "60 min", speakers: ["Jake Park, CIO", "Specfin Investment Team"], attendees: 487, virtual: true },
  { id: 2, type: "Deep Dive", typeColor: "#0D3880", title: "From LPU to edge AI: Groq vs Hailo vs NVIDIA — the inference chip landscape for investors", description: "A technical and investment deep dive into the full AI inference chip sector — from cloud LPUs (Groq) to edge processors (Hailo). Understanding the architecture differences and market opportunity for each.", date: "2026-07-17", time: "6:00 PM KST", duration: "45 min", speakers: ["Dr. David Choi, Technical Advisor"], attendees: 312, virtual: true },
  { id: 3, type: "Summit", typeColor: "#EFC878", title: "Specfin Seoul Private Market Summit 2026", description: "First annual in-person summit in Seoul. Portfolio company presentations, keynotes from the founding team, co-hosted with Ark Global. Includes a panel on OurCrowd's Korea-Israel Fund investments.", date: "2026-08-22", time: "9:00 AM KST", duration: "Full day", speakers: ["Jake Park, CEO", "Min-Ji Lee, CTO", "Ark Global Team"], attendees: 156, virtual: false, location: "Grand InterContinental Seoul, Gangnam" },
  { id: 4, type: "Masterclass", typeColor: "#9F84FF", title: "How to evaluate pre-IPO tech: SpaceX, Anthropic, xAI — cap tables, dilution, exit math", description: "A masterclass on evaluating late-stage private market investments. Worked examples with SpaceX, Anthropic, and xAI: reading cap tables, modeling dilution across rounds, and calculating realistic exit returns.", date: "2026-07-24", time: "5:00 PM KST", duration: "75 min", speakers: ["Specfin Investment Committee"], attendees: 543, virtual: true },
];

export const PORTFOLIO_HOLDINGS = [
  { id: 1, name: "Anthropic (Series G SPV)", type: "Growth Equity", invested: 25000, currentValue: 41250, returnPct: 65.0, status: "Active", since: "2024-08-15", currency: "USD" },
  { id: 2, name: "Databricks (Series J)", type: "Growth Equity", invested: 50000, currentValue: 78500, returnPct: 57.0, status: "Active", since: "2024-11-20", currency: "USD" },
  { id: 3, name: "Groq (Series B SPV)", type: "Venture", invested: 10000, currentValue: 14200, returnPct: 42.0, status: "Active", since: "2024-06-01", currency: "USD" },
  { id: 4, name: "ZutaCore (Series B)", type: "Venture", invested: 5000, currentValue: 6800, returnPct: 36.0, status: "Active", since: "2024-03-10", currency: "USD" },
];

export const ASSET_CLASSES = [
  { icon: "🚀", title: "Growth Equity (Pre-IPO)", description: "Late-stage private companies preparing for IPO. Access Anthropic, Databricks, SpaceX, and xAI before they go public — the stage where institutional returns are typically made.", href: "/dashboard/opportunities?type=growth-equity", stats: "4 open · Avg. $500B+ valuation", color: "#0D3880" },
  { icon: "⚡", title: "Venture Capital", description: "Series A-C technology startups across AI infrastructure, deep tech, and cybersecurity. OurCrowd-sourced deals from Israel's most active VC ecosystem, co-invested with top global funds.", href: "/dashboard/opportunities?type=venture", stats: "6 opportunities · $5K min", color: "#00A896" },
  { icon: "🏢", title: "Real World Assets (RWA)", description: "Tokenized fractional ownership of commercial real estate, blue-chip art, and physical collectibles. Quarterly USDT dividends. Secondary market liquidity. Live NAV on-chain. Launching Phase 2.", href: "/dashboard/opportunities?type=rwa", stats: "Phase 2 launching Q3 2026", color: "#7C3AED" },
];

export const LEARN_ARTICLES = [
  { id: 1, category: "Getting Started", title: "How to evaluate a pre-IPO investment on Specfin", description: "A complete guide to reading a term sheet, understanding carry and management fees, and assessing the exit path for late-stage private companies like Anthropic and SpaceX.", readTime: "6 min" },
  { id: 2, category: "AI Investing", title: "The AI stack: where Anthropic, Groq, Hailo, and Databricks fit", description: "A visual framework for the AI value chain — from silicon (Groq, Hailo) to models (Anthropic) to data platforms (Databricks) — and where OurCrowd-backed companies sit.", readTime: "7 min" },
  { id: 3, category: "Portfolio Strategy", title: "How to build a diversified private market portfolio", description: "Stage diversification, sector balance, and position sizing for a private market portfolio. Lessons from OurCrowd's 480+ company portfolio across Israel and the US.", readTime: "5 min" },
  { id: 4, category: "Tax & Legal", title: "SPVs explained: how Specfin structures co-investments", description: "Special Purpose Vehicles are the legal structure used for most co-investment deals. How they work, what you own, and how exit distributions flow back to investors.", readTime: "5 min" },
  { id: 5, category: "Risk Management", title: "Liquidity risk in private markets: what you need to know", description: "Private market investments are illiquid by design. Lock-up periods, secondary market options, and how to think about liquidity needs before investing in pre-IPO deals.", readTime: "6 min" },
];
